"""add title_snapshot to note_versions

Revision ID: 0a593d2d6430
Revises: 32f756f7bd02
Create Date: 2026-01-11 02:24:15.931077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a593d2d6430'
down_revision: Union[str, Sequence[str], None] = '32f756f7bd02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add column as nullable
    op.add_column(
        'note_versions',
        sa.Column('title_snapshot', sa.String(), nullable=True)
    )

    # 2. Backfill title_snapshot from notes table
    op.execute("""
        UPDATE note_versions
        SET title_snapshot = notes.title
        FROM notes
        WHERE note_versions.note_id = notes.id
    """)

    # 3. Make column NOT NULL
    op.alter_column(
        'note_versions',
        'title_snapshot',
        nullable=False
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note_versions', 'editor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('note_versions', 'note_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('note_versions', 'title_snapshot')
    # ### end Alembic commands ###
