"""add activity logs

Revision ID: 1e6bdcdf9bce
Revises: 0a593d2d6430
Create Date: 2026-01-12 16:25:17.364757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6bdcdf9bce'
down_revision: Union[str, Sequence[str], None] = '0a593d2d6430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('note_versions', 'note_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('note_versions', 'editor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note_versions', 'editor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('note_versions', 'note_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
